### ISSUE TITLE
Null check missed in expression with conditional operator

### ISSUE THREAD

**Issue by emsod** [google/simplecfg#11]
This code currently fails:

int test(@Nullable String p) {
  if (p == null || (true ? p.size() != 1 : false) {
    return 1;
  }
  return 2;
}

But the following works:

int test(@Nullable String p) {
  if (p == null || p.size() != 1) {
    return 1;
  }
  return 2;
}

The culprit appears to be the conditional operator.

**Comment by llbit** [comment]
I could not reproduce this issue. I added a test file containing the code you suggested as test case, and it seems to work. I'll create a pull request with the added test.

**Comment by llbit** [comment]
I made a mistake in my test case - I forgot to import `javax.annotation.Nullable`. Now I am able to reproduce the false positive.
